main: fr.studioevident.tpplot.TpPlot
name: TpPlot
version: 1.0
api-version: 1.19
author: StudioEvident
depend: [ WorldGuard ]
commands:
  tpplot:
    description: "Allow players to tp to WorldGuard plots."
    usage: /tpplot [player] [plotName]
